<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Deepak-Kumar-LP" failures="1" tests="5" name="Personal Loan" time="0.069" errors="0" timestamp="2022-11-07T12:00:49 IST">
  <testcase classname="test.day2" name="ploan" time="0.006"/>
  <testcase classname="test.day1" name="Demo" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.Demo(day1.java:14)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.day4" name="LoginApiHomeLoan" time="0.001"/>
  <testcase classname="test.day4" name="MobileloginHomeLoan" time="0.003"/>
  <testcase classname="test.day4" name="WebloginHomeLoan" time="0.002"/>
  <testcase classname="test.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
